// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAg-1oPVnMnP0apgmUU1l7K0MSDdxc7KDg',
    appId: '1:123173143377:web:03a3bd3cc7caf05c148970',
    messagingSenderId: '123173143377',
    projectId: 'tryfire-167e0',
    authDomain: 'tryfire-167e0.firebaseapp.com',
    storageBucket: 'tryfire-167e0.appspot.com',
    measurementId: 'G-664RLW29TS',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDV4-6DDhhV5Mjh2edFmJ2c54kZjnfESwE',
    appId: '1:123173143377:android:a5808e8579d4e74c148970',
    messagingSenderId: '123173143377',
    projectId: 'tryfire-167e0',
    storageBucket: 'tryfire-167e0.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCAQ-TRS9y-7nZeITlnUb58VYaN_oaiHXM',
    appId: '1:123173143377:ios:3600fb88ca185647148970',
    messagingSenderId: '123173143377',
    projectId: 'tryfire-167e0',
    storageBucket: 'tryfire-167e0.appspot.com',
    iosBundleId: 'com.example.hustling',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCAQ-TRS9y-7nZeITlnUb58VYaN_oaiHXM',
    appId: '1:123173143377:ios:3600fb88ca185647148970',
    messagingSenderId: '123173143377',
    projectId: 'tryfire-167e0',
    storageBucket: 'tryfire-167e0.appspot.com',
    iosBundleId: 'com.example.hustling',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAg-1oPVnMnP0apgmUU1l7K0MSDdxc7KDg',
    appId: '1:123173143377:web:28a52ae939ec480d148970',
    messagingSenderId: '123173143377',
    projectId: 'tryfire-167e0',
    authDomain: 'tryfire-167e0.firebaseapp.com',
    storageBucket: 'tryfire-167e0.appspot.com',
    measurementId: 'G-K25ZRBKZP0',
  );
}
